version: "3"

services:
  light-image-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "16524:16524"
    restart: unless-stopped
    # 可选：自定义命令行参数
    # command: -port=16524 -timeout=30 -log=true
    # 可选：设置资源限制
    deploy:
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 20M
